/**
 * Reads/writes the committed JSON audit reports in `server/data/`.
 *
 * These files are the "demo mode" seed data — generated by
 * `engine/scripts/generate_reports.py` and checked into the repo so the
 * dashboard has real, representative numbers to render even before
 * anyone has installed the Python dependencies. `POST /api/audits/:domain/run`
 * overwrites the relevant file with a fresh live run.
 */

import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const DATA_DIR = path.resolve(__dirname, "../../data");

export async function listAudits() {
  const indexPath = path.join(DATA_DIR, "index.json");
  const raw = await fs.readFile(indexPath, "utf-8");
  return JSON.parse(raw);
}

export async function getAuditReport(domain) {
  const reportPath = path.join(DATA_DIR, `${domain}.json`);
  try {
    const raw = await fs.readFile(reportPath, "utf-8");
    return JSON.parse(raw);
  } catch (err) {
    if (err.code === "ENOENT") return null;
    throw err;
  }
}

export async function saveAuditReport(domain, report) {
  const reportPath = path.join(DATA_DIR, `${domain}.json`);
  await fs.writeFile(reportPath, JSON.stringify(report, null, 2));
  await refreshIndexEntry(domain, report);
  return report;
}

async function refreshIndexEntry(domain, report) {
  const indexPath = path.join(DATA_DIR, "index.json");
  let index;
  try {
    index = JSON.parse(await fs.readFile(indexPath, "utf-8"));
  } catch {
    index = { generated_by: "server", domains: [] };
  }

  const entry = {
    domain,
    overall_severity_score: report.overall_severity_score,
    overall_severity_tier: report.overall_severity_tier,
    gate_pass: report.gate_pass,
    n_test_samples: report.n_test_samples,
    generated_at: report.generated_at,
  };

  const idx = index.domains.findIndex((d) => d.domain === domain);
  if (idx >= 0) index.domains[idx] = entry;
  else index.domains.push(entry);

  await fs.writeFile(indexPath, JSON.stringify(index, null, 2));
}
